server:
  port: 8888

spring:
  application:
    name: ecommerce-config-server
  cloud:
    config:
      server:
        git:
          uri: file:///Users/kigibiin/Documents/00_workspace/95_MSA/git-local-repo